// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0undQ_N8Uas70cw-afTUPJX5Ufa_Ykg',
    appId: '1:936797446486:web:5c21b8b6e6e4fe8db976f7',
    messagingSenderId: '936797446486',
    projectId: 'my-jop-9c874',
    authDomain: 'my-jop-9c874.firebaseapp.com',
    storageBucket: 'my-jop-9c874.appspot.com',
    measurementId: 'G-C89R5EQ52N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7n_DSqO8yUIMAQXZs9g-rV3ymAU8v5w0',
    appId: '1:936797446486:ios:284ca18eed7fc24fb976f7',
    messagingSenderId: '936797446486',
    projectId: 'my-jop-9c874',
    storageBucket: 'my-jop-9c874.appspot.com',
    iosBundleId: 'com.example.myJobDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs0undQ_N8Uas70cw-afTUPJX5Ufa_Ykg',
    appId: '1:936797446486:web:c9679d61517891aab976f7',
    messagingSenderId: '936797446486',
    projectId: 'my-jop-9c874',
    authDomain: 'my-jop-9c874.firebaseapp.com',
    storageBucket: 'my-jop-9c874.appspot.com',
    measurementId: 'G-KEMXSP1EQL',
  );
}
