// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtoqs2u83Ch1IZ8XHg-ThzbX20c8nZ4L8',
    appId: '1:865050411490:web:0cc1a0c8b8952b78f139bb',
    messagingSenderId: '865050411490',
    projectId: 'job-flutter-1a23b',
    authDomain: 'job-flutter-1a23b.firebaseapp.com',
    storageBucket: 'job-flutter-1a23b.appspot.com',
    measurementId: 'G-5TX3KM3C1P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZldImTx5zuYEHjYpdMsIXZNIb7QmY48s',
    appId: '1:865050411490:ios:4e5dec82f4b226a7f139bb',
    messagingSenderId: '865050411490',
    projectId: 'job-flutter-1a23b',
    storageBucket: 'job-flutter-1a23b.appspot.com',
    iosBundleId: 'com.example.myJobDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtoqs2u83Ch1IZ8XHg-ThzbX20c8nZ4L8',
    appId: '1:865050411490:web:0a8671eea790e455f139bb',
    messagingSenderId: '865050411490',
    projectId: 'job-flutter-1a23b',
    authDomain: 'job-flutter-1a23b.firebaseapp.com',
    storageBucket: 'job-flutter-1a23b.appspot.com',
    measurementId: 'G-4TMHFK7JFM',
  );
}
